server:
  port: 8082

spring:
  application:
    name: currency-service

  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
