server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/unitech_auth
    username: postgres
    password: gunel1969
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update #validate in production
    show-sql: true #false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest

  data:
    redis:
      url: "redis://localhost:6379"
      connect-timeout: 3s

app:
  jwt:
    secret: "roxkA8P+1j2Z6Z/sDSNtJ6mQcekYhTPkjFMgPPvEZr4="
    access-token-expiration: 900000  #15mins
    refresh-token-expiration: 604800000 #7days

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO                   # Default level for everything
    org.springframework.security: WARN  # Security logs only warnings+
    com.unitech: DEBUG           # Your app code shows debug messages
    org.hibernate.SQL: DEBUG     # Shows all SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Shows query parameters