server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/unitech_auth
    username: postgres
    password: gunel1969
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #change it later
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/